name = "sw-vtt-rooms-worker"
main = "worker.js"
compatibility_date = "2026-02-12"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomDO"]
